Exclude EndToEndTest.SendsAndReceivesH264 for Dr Memory.
This test is too slow to execute:
[ RUN      ] EndToEndTest.SendsAndReceivesH264
e:\b\build\slave\win-drmem\build\src\webrtc\video\end_to_end_tests.cc(287): error: Value of: Wait()
  Actual: 3
Expected: kEventSignaled
Which is: 1
Timed out while waiting for enough frames to be decoded.
[  FAILED  ] EndToEndTest.SendsAndReceivesH264 (72812 ms)

BUG=3159
R=pbos@webrtc.org

Review URL: https://webrtc-codereview.appspot.com/38599004